[package]
name = "rust_retry_backon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
backon = "1.2.0"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
rand = "0.8.5"
