name: build-go-projects

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
    paths:
      - 'operator/**'
      - 'aggregator/**'
      - 'common/**'
      - 'core/**'
      - 'metrics/**'
      - '.github/workflows/build-go.yml'
env:
  FFI_FOR_RELEASE: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear device space
        run: |
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Operator and ffi bindigs
        run: |
          make build_operator
      - name: Test Operator
        run: |
          make test_operator
      - name: Build aggregator
        run: go build aggregator/cmd/main.go
      - name: Test aggregator
        run: go test ./aggregator/...
