name: build-go-projects

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
    paths:
      - 'operator/**'
      - 'aggregator/**'
      - 'common/**'
      - 'core/**'
      - 'metrics/**'
      - '.github/workflows/build-go.yml'
env:
  FFI_FOR_RELEASE: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Build all ffi
        run: |
          LD_LIBRARY_PATH=/usr/lib:/usr/local/lib # needs to set a default value, as the make command expects it
          make build_all_ffi
      - name: Test all ffi
        run: make test_all_ffi
      - name: Test operator
        run: |
          go test ./operator/cmd/...
          go test ./operator/pkg/...
      - name: Build aggregator
        run: go build aggregator/cmd/main.go
      - name: Test aggregator
        run: go test ./aggregator/...
