name: Docker build and push

on:
  push:
    branches:
      - docker-compose

jobs:
  docker-build-push:
    name: Build docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Docker image
      run: |
        make docker_build_aggregator

    - name: Push Docker image
      run: |
        docker push ghcr.io/lambdaclass/aligned_layer/aggregator:v0.8.0
