name: "[CI] Send proofs to network"

on:
  push:
    branches:
      - docker-compose

jobs:
  network-test-docker-compose:
    name: "Test network with Docker Compose"
    timeout-minutes: 15
    runs-on: aligned-runner-ci
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build containers
      run: make docker_build

    - name: Start containers and initialize network
      run: make docker_up && sleep 15

    - name: Send proofs batches
      run: make docker_batcher_send_all_proofs_burst

    - name: Verify all sent proofs
      run: make docker_verify_proof_submission_success

  post-cleanup:
    name: "Cleanup"
    runs-on: docker
    if: ${{ always() }}
    needs: network-test-docker-compose

    steps:
    - name: Stop containers
      continue-on-error: true
      if: always()
      run: make docker_down

    - name: Delete _work
      if: always()
      run: sudo rm -rf /home/admin/actions-runner/_work/aligned_layer/
