name: Test

on:
  push:
    branches:
      - docker-compose

jobs:
  docker:
    timeout-minutes: 30
    runs-on: docker
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: make docker_up && sleep 15

    - name: Send proofs batches
      run: make docker_batcher_send_all_proofs_burst

    - name: Verify all sent proofs
      run: make docker_verify_proof_submission_success

  post:
    runs-on: docker
    needs: docker

    steps:
    - name: Stop containers
      if: always()
      run: make docker_down

    - name: Delete _work
      if: always()
      run: sudo rm -rf /home/admin/actions-runner/_work/aligned_layer/
