name: Test

on:
  push:
    branches:
      - docker-compose

jobs:
  docker:
    runs-on: docker

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build containers
      run: make docker_build

    - name: Start containers
      run: make docker_up

    - name: Logs
      run: sleep 30 && docker-compose -f "docker-compose.yaml" logs

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yaml" down
