name: Test

on:
  push:
    branches:
      - docker-compose

jobs:
  docker:
    timeout-minutes: 30
    runs-on: docker

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOMI_GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: sudo make docker_up

    - name: Stop containers
      if: always()
      run: sudo make docker_down
