name: Test

on:
  push:
    branches:
      - docker-compose

jobs:
  docker:
    timeout-minutes: 30
    runs-on: docker

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: sudo make docker_up

    - name: Stop containers
      if: always()
      run: sudo make docker_down
