name: test-nexus

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - "operator/nexus/**"
      - ".github/workflows/test-nexus.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test Nexus Rust
        run: make test_nexus_rust_ffi
      - name: Test Nexus go bindings
        run: make test_nexus_go_bindings_linux
